	DELETE FROM app;
	DELETE FROM challenge;
	DELETE FROM challenge_con_user;
	DELETE FROM friend;
	DELETE FROM game;
	DELETE FROM history;
	DELETE FROM session;
	DELETE FROM setting;
	DELETE FROM type;
	DELETE FROM user;
	DELETE FROM user_con_app;
	DELETE FROM menu;


/* RESET AUTOINCREMENT */

	ALTER TABLE app AUTO_INCREMENT = 0;
	ALTER TABLE challenge AUTO_INCREMENT = 0;
	ALTER TABLE challenge_con_user AUTO_INCREMENT = 0;
	ALTER TABLE friend AUTO_INCREMENT = 0;
	ALTER TABLE game AUTO_INCREMENT = 0;
	ALTER TABLE history AUTO_INCREMENT = 0;
	ALTER TABLE session AUTO_INCREMENT = 0;
	ALTER TABLE setting AUTO_INCREMENT = 0;
	ALTER TABLE type AUTO_INCREMENT = 0;
	ALTER TABLE user AUTO_INCREMENT = 0;
	ALTER TABLE user_con_app AUTO_INCREMENT = 0;